name = "The Hive - Server Utils - Hyerakon"; // name
tooltip = "The Hive - Server Utils - Hyerakon"; // tool tip on mouse hover
overview = "This mod is a custom Vanilla and Expansion Bundle–based Utilities collection, developed exclusively for a private DayZ server and for my personal testing purposes."; // overview
action = "https://www.thehivemind.it/"; // link
author = "Hyerakon"; // author
version = "1.0"; // version
picture = "TheHive_Server_Utilities\data\thehive_filigrana.edds";
logoSmall = "TheHive_Server_Utilities\data\thehive_filigrana.edds";
logo = "TheHive_Server_Utilities\data\thehive_filigrana.edds";
logoOver = "TheHive_Server_Utilities\data\thehive_filigrana.edds";