name = "The Hive - Item & Gears - Hyerakon"; // name
tooltip = "The Hive - Item & Gears - Hyerakon"; // tool tip on mouse hover
overview = "This mod is a custom Vanilla and Expansion Bundle–based Gear and Equipment collection, developed exclusively for a private DayZ server and for my personal testing purposes."; // overview
action = "https://www.thehivemind.it/"; // link
author = "Hyerakon"; // author
version = "1.0"; // version
picture = "TheHive_Server_Utilities/data/thehive_filigrana.edds";
logoSmall = "TheHive_Server_Utilities/data/thehive_filigrana.edds";
logo = "TheHive_Server_Utilities/data/thehive_filigrana.edds";